# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post2',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post2',
        ),
    ]
